// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cumyjcpfjlyjhmujkmzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1bXlqY3Bmamx5amhtdWprbXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MDkxNDksImV4cCI6MjA3NTM4NTE0OX0.kYJd3fWMVz8vr1oWl_yfGOB8XqkmMlUtU4Oy8LCFses";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});